services:
  - type: web
    name: agrovoice
    env: node
    buildCommand: npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
